p8105\_hw1\_ew2717
================
Eric Wang

## Problem 1

``` r
set.seed(10)

data_table <- tibble(
  my_variable = rnorm(10),
  logical_vec = my_variable > 0,
  ten_char_vector = c("c", "h", "a", "r", "a", "c", "t", "e", "r", "s"),
  three_levels = factor(c("one", "two", "three", "three", "two", "one", "one", "one", "three", "three"))
)

data_table
```

    ## # A tibble: 10 x 4
    ##    my_variable logical_vec ten_char_vector three_levels
    ##          <dbl> <lgl>       <chr>           <fct>       
    ##  1      0.0187 TRUE        c               one         
    ##  2     -0.184  FALSE       h               two         
    ##  3     -1.37   FALSE       a               three       
    ##  4     -0.599  FALSE       r               three       
    ##  5      0.295  TRUE        a               two         
    ##  6      0.390  TRUE        c               one         
    ##  7     -1.21   FALSE       t               one         
    ##  8     -0.364  FALSE       e               one         
    ##  9     -1.63   FALSE       r               three       
    ## 10     -0.256  FALSE       s               three

``` r
mean(pull(data_table, my_variable))
```

    ## [1] -0.4906568

``` r
mean(pull(data_table, logical_vec))
```

    ## [1] 0.3

``` r
mean(pull(data_table, ten_char_vector))
```

    ## Warning in mean.default(pull(data_table, ten_char_vector)): argument is not
    ## numeric or logical: returning NA

    ## [1] NA

``` r
mean(pull(data_table, three_levels))
```

    ## Warning in mean.default(pull(data_table, three_levels)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

The mean of my\_variable and logical\_vec can be calculated because they
are numeric and logical vectors. ten\_char\_vector and three\_levels,
however, cannot have their means calculated because they are character
and factor vectors.

``` r
converted_num1 = as.numeric(pull(data_table, logical_vec))
converted_num2 = as.numeric(pull(data_table, ten_char_vector))
converted_num3 = as.numeric(pull(data_table, three_levels))
```

The logical and factor vectors can be converted to numeric values, while
the character value cannot be converted. We are unable to convert
characters or letters to numbers. For the logical vector, we are able to
convert it to numeric because 1 can represent TRUE and 0 can represent
FALSE.

``` r
mean(converted_num1)
```

    ## [1] 0.3

``` r
mean(converted_num2)
```

    ## [1] NA

``` r
mean(converted_num3)
```

    ## [1] 1.8

After converting logical\_vec, ten\_char\_vector, and three\_levels to
numeric values, it is found that only ten\_char\_vector cannot be
converted. I could not convert the chracater vector into numeric
variables.

# Problem 2

``` r
data("penguins", package = "palmerpenguins")
```

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

The variable names from this data set include species, island,
bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g,
sex, and year.

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

The values of important variables includes an average of 43.9mm for bill
length, 17.2mm for bill depth, 201mm for flipper length, 4202g for body
mass, and 2008 for year.

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

There are 344 rows and 8 columns in this data set.

The mean flipper length is 201.

``` r
ggplot(penguins, aes(x = flipper_length_mm, y = bill_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ew2717_files/figure-gfm/create%20and%20output%20scatter%20plot-1.png)<!-- -->

``` r
ggsave("penguin_scatter_plot.pdf", plot = last_plot(), height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
